##  服务端口
server:
  port: 8085
##  服务名称
spring:
  application:
    name: pay-server
##  eureka配置
eureka:
  client:
    service-url:
      defaultZone:   http://localhost:8080/eureka/
  instance:
    status-page-url: http://localhost:8081/eureka//swagger-ui.html
##  日志
logging:
  level:
    root: info
    com:
      netflix:
        eureka: 'off'
        discovery:  'off'
## 关闭管理类接口的安全认证
management:
  security:
    enabled: false
