zuul:
  routes:
    demo-pay-server:
      path: /pay/**
    demo-server:
      path: /order/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ribbon-isolation-strategy: thread
