# eureka(最)简单开发配置。支持yml与properties两种，yml文件后缀必须为yml，不能是yaml，否则找不到该文件，使用默认配置。
# yml文件大小写敏感；
# 每个级别至少用1个空格缩进，也可多个，但同级别的必须一致，不支持tab，本项目按照eclipse的插件（spring官方Spring Tool Suite3.9.3）统一使用两个空格；
# 属性值与冒号间必须有一个空格。比如port:8761则不会生效。
# eureka服务器端口号。尽管无论官网还是大部分参考书都使用8761，但默认并不是，而是8080
server:
  port: 8080
##  服务名称
spring:
  application:
    name: demo-eureka
##  eureka配置
eureka:
  # 自我保护机制，默认true。打开后，心跳失败在15分钟内低于85%(renewalPercentThreshold)的服务，也不进行剔除。
  # 关闭后，主页提示：RENEWALS ARE LESSER THAN THE THRESHOLD. THE SELF PRESERVATION MODE IS TURNED OFF.
  server:
    enable-self-preservation: false # 本地调试时可fasle关闭。但生产建议打开，可防止因网络不稳定等原因导致误剔除服务
    renewalPercentThreshold: 0.85 # 默认85%
  client:
    # 默认情况下，eureka server同时也是eureka client，用于相互注册形成高可用eureka服务。
    # 单点时，如果registerWithEureka配置为true，则eureka server会报错Cannot execute request on any known server
    register-with-eureka: true # 是否注册到eureka服务，默认为true，如果已为eureka server，且单点eureka，配置为false
    fetch-registry: false # 是否在本地缓存注册表信息，默认为true，当前为单点eureka server，不需要从其他eureka除获取注册表信息，更谈不上缓存，故配置为false
    service-url:
      # registerWithEureka关闭后，defaultZone没有配置的必要。如果打开，即使配置为本机一样报错。
      # 也就是说defaultZone任何时候都没有配置为localhost的必要。
      # 但对于server来说，这个默认没有什么作用。对于client来说，也只有调试的时候有点作用。
      # 但有一点很奇怪，既然默认了8761端口，为什么eureka server的默认端口要用8080而不是8761呢？
      defaultZone:   http://localhost:${server.port}/eureka/  # 本配置应删除
##  日志
logging:
  level:
    root: info
    com:
      netflix:
        eureka: 'off'
        discovery:  'off'
## 关闭管理类接口的安全认证
management:
  security:
  enabled: false